### ISSUE TITLE
Конфигурация работает только 8.3.10.ххх?

### ISSUE THREAD

**Issue by BlizD** [Stepa86/1C-Gitter#1]
Конфигурация работает только 8.3.10.ххх?
Попробовал загрузить конфигурацию выдает сообщение:

![image](https://cloud.githubusercontent.com/assets/10989306/25311814/0799271e-2813-11e7-958e-5bf8236fd68e.png)

**Comment by Stepa86** [comment]
Гиттер как раз хорош для инкрементальной выгрузки, что есть только в 8.3.10+
Режим совместимости понизил до 8.3.6, думаю этого будет достаточно
