### ISSUE TITLE
Каталог, куда выгружаются исходники должен быть именно тем, который указан в настройках

### ISSUE THREAD

**Issue by JohnyDeath** [Stepa86/1C-Gitter#2]
Сейчас к нему автоматом прицепляется "src"
Это будет проблемой, если вы пытаетесь разрабатывать правильно и проект разложен по папочкам в стиле https://github.com/silverbulleters/vanessa-bootstrap

**Comment by Stepa86** [comment]
Теперь каталог src можно переопределить в настройках
