### ISSUE TITLE
Перед Push надо обязательно делать Pull

### ISSUE THREAD

**Issue by JohnyDeath** [Stepa86/1C-Gitter#3]
Если вы работаете не один и кто-то параллельно, например, складывает в удаленный репо внешние отчеты и обработки, то необходимо сначала актуализировать текущий локальный репозиторий, а уже потом отправлять изменения.

**Comment by Stepa86** [comment]
Я не знаю что делать, если изменения пришли именно в исходниках конфы. Просто пулл, а затем пуш все затрет, а чтобы сливать с хранилищем - нужен человек, который и может сперва пулл сделать.

**Comment by JohnyDeath** [comment]
А почему изменяются исходники конфы? Они же напрямую из хранилища тянутся. Других изменений быть не должно.
Гитсинк так и работает

**Comment by Stepa86** [comment]
А если будут? Вот в этот репо запулреквестят изменения по гиттеру. Как сливаться? По умолчанию и в фоне получать изменения опасно, а делать сливалку и контроль непонятно как, да и муторно.

**Comment by JohnyDeath** [comment]
Как они буду-то? Кто-то у вас параллельно в EDT работает без хранилища?
Если при пулл-е будет конфлик - то выбрасывать исключение.
Но я пока на такое не нарывался ни разу за 5 лет использования гитсинка и их его предков

**Comment by JohnyDeath** [comment]
Я там немного прокомментировал код в двух местах
