### ISSUE TITLE
Чтение списка пользователей из файла

### ISSUE THREAD

**Issue by JohnyDeath** [Stepa86/1C-Gitter#4]
Хотелось бы иметь возможность периодического считывания пользователей хранилища для последующего занесения в справочник пользователей из текстового файла, указанных в настройке (новой настройке).
Периодически отваливается синхронизация именно по причине появления нового пользователя. Сейчас каждый новый разработчик вносит себя в текстовик, откуда его приходится руками переносить в гиттер.
Файл формата gitsync:

`razrab_1=Иванов Иван <i.ivanov@mail.coma>`

**Comment by Stepa86** [comment]
Если честно, это какой то адовый костыль. Читать из файла, который вообще то является служебным для другого продукта, совершенно не нравится. Но как сделать по другому пока не могу придумать.

**Comment by Stepa86** [comment]
Добавить себя в спец. файл и добавить себя в спец. справочник не сильно по трудозатратам отличается. Просто в гитсинхе сделано по одному, в гиттере по другому

**Comment by JohnyDeath** [comment]
Никто вообще не знает про Гиттер и вирт машину, на которой он крутиться. 
Давать к нему доступ всем подряд не хочется

**Comment by PiskunovSS** [comment]
Как насчет создания справочника и регистра сведений, который будет содержать соответствие имени пользователя хранилища, с его email и правильным ФИО для коммитов? А этот справочник можно заполнять регламентным заданием с произвольным алгоритмом на основе ИР. Кто-то может из файла читать, кто-то еще может дергать откуда-то, например с локального почтового сервера. Мы сделали для себя табдок с таким соответствием и сохранили его в конфигурацию. При получении пользователей из хранилища идет поиск имени из хранилища в колонке ФИО из табдока. Понятно, что костыль, но работает неплохо, пока новый разработчик не появится.

**Comment by Stepa86** [comment]
@PiskunovSS В гиттере пользователи как раз на справочнике хранятся
