### ISSUE TITLE
Установка пользователя при коммите

### ISSUE THREAD

**Issue by alyaevav** [Stepa86/1C-Gitter#6]
Если в полном наименовании пользователя будет строка с пробелом(например "Имя Фамилия"), то user.name не устанавливается, как я понял кавычек не хватает.

**Comment by Stepa86** [comment]
Этот ишуз видел, но когда руки дойдут - не знаю. Попробуйте на своей базе добавить кавычки - ошибка уйдет?

**Comment by alyaevav** [comment]
Пробовал, но там потом вызов процедуры конфиг и в ней убиваются кавычки:
`Процедура Config( ЛокальныйРепозиторийАдрес, Параметр, Знач Значение, ЭкранироватьЗначение = Ложь )
	
	Если ЭкранироватьЗначение Тогда
		
		Значение = Экранировать( Значение );
		
	КонецЕсли;`

У себя я приделал костылик в вызов "Config", вот так работает:
`Процедура СконфигурироватьИмяПользователя( ЛокальныйРепозиторийАдрес, Имя ) Экспорт
	
	Config( ЛокальныйРепозиторийАдрес, "user.name", """" + Имя + """", Ложь );
	
КонецПроцедуры`
