### ISSUE TITLE
Удалять все файлы исходников при полной выгрузке

### ISSUE THREAD

**Issue by JohnyDeath** [Stepa86/1C-Gitter#7]
Если выгрузка не инкрементальная, а полная, то необходимо делать предварительную полную очистку каталога исходников, чтобы вычистить все удаленные объекты.
Пример с PR для гитсинка: https://github.com/oscript-library/gitsync/pull/100/files#diff-a0d168b67d7f3ec53448fe3e8b2b1106R120

**Comment by Stepa86** [comment]
Вообще то это первое, что я запилил в Гиттере. Оно не работает?

**Comment by JohnyDeath** [comment]
Я по гиту не заметил удалений файлов.
Специально смотрел коммиты, где удаляют объекты. Есть изменение внутренностей, но в исходниках сами объекты так и лежат

**Comment by Stepa86** [comment]
@JohnyDeath Я попробовал добавить и удалить константу - ее файлы были удалены и Гиттер отработал корректно - зачистил всю папку, а потом выгрузил все. Смотри коммит https://github.com/Stepa86/1C-Gitter/commit/716e56acdff555b1aee9a232cdce2884d5d91cdb

Проверь у себя, что при удалении объекта 
1. Ставится флаг https://github.com/Stepa86/1C-Gitter/blob/master/src/CommonModules/%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D1%8B%D0%B9%D0%A0%D0%B5%D0%B6%D0%B8%D0%BC/Ext/Module.bsl#L122
2. заходит в метод https://github.com/Stepa86/1C-Gitter/blob/master/src/Catalogs/%D0%A5%D1%80%D0%B0%D0%BD%D0%B8%D0%BB%D0%B8%D1%89%D0%B0/Ext/ManagerModule.bsl#L577 
3. и что каталог реально чистится

**Comment by JohnyDeath** [comment]
ок, понаблюдаю внимательней при следующем удалении.
Просто таких помещений было штук 7 почти подряд (чистили объекты с префиксом "удалить"). В исходниках всё так и осталось висеть

**Comment by JohnyDeath** [comment]
Воспроизвести пока не удалось.
Закрываю
